### ISSUE TITLE
feature-AccountsBaseTemplate

### ISSUE THREAD

**Issue by Sunny3939hum** [THChen2002/AI-Interview-Bot#28]
1. 建立AccountsBase.html
2. 修改關於註冊-登入畫面的html 繼承AccountsBase.html

**Comment by THChen2002** [comment]
- [ ] accounts第11行空格刪除
- [ ] index.html 內容不是這單
- [ ] register.html第28行縮排
- [ ] reset_password_complete.html <script>放在最外面
- [ ] reset_password_complete.html 第32-33行改成JQuery
